name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Verificar versão do Node.js
        run: node -v

      - name: Instalar dependências do frontend
        run: |
          cd frontend
          npm install

      - name: Instalar dependências do backend
        run: |
          cd backend
          npm install

      - name: Rodar testes do frontend
        run: |
          cd frontend
          npm test

      - name: Rodar testes do backend
        run: |
          cd backend
          npm test

      - name: Verificar instalação do Terraform
        run: terraform -version

      - name: Deploy para AWS
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve